<?php
# This file was automatically generated by the MediaWiki 1.26.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Pivot Learning Wiki";
$wgMetaNamespace = "Pivot_Learning_Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://pivotpedia.pivotlearning.org";


## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/pivotwiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@pivotwiki-env.us-west-1.elasticbeanstalk.com";
$wgPasswordSender = "apache@pivotwiki-env.us-west-1.elasticbeanstalk.com";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "aagj3rvoqtjbru.cg3rmgk8n7ah.us-west-1.rds.amazonaws.com:3306";
$wgDBname = "ebdb";
$wgDBuser = "pivotwiki";
$wgDBpassword = "pivot500";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "08593f845b5148b761bdb6c341b09aaaab63659d04c1f74726b0523a5792c147";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "18ebcfd55ba28049";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );


# End of automatically generated settings.
# Add more configuration options below.

$wgAllowExternalImages = "true";
$wgEnableUploads = true; #Enable uploads

#ckeditor settings

#13.11.13->
require_once( "$IP/extensions/WYSIWYG/WYSIWYG.php" );

# Examples of setting permissions using $wgGroupPermissions, for more detailed explanation see:
#   https://www.mediawiki.org/wiki/Manual:$wgGroupPermissions#Example
# $wgGroupPermissions['user']['wysiwyg'] = true; //Only registered users are allowed to use wysiwyg
# $wgGroupPermissions['*']['wysiwyg'] = true;    //Everyone is allowed to use wysiwyg
$wgGroupPermissions['*']['wysiwyg'] = true;

$wgDefaultUserOptions['cke_show'] = 'richeditor';    //Enable CKEditor
$wgDefaultUserOptions['riched_use_toggle'] = false;  //Editor can toggle CKEditor/WikiText
$wgDefaultUserOptions['riched_start_disabled'] = false; //Important!!! else bug...
$wgDefaultUserOptions['riched_toggle_remember_state'] = true; //working/bug?
$wgDefaultUserOptions['riched_use_popup'] = false;   //Deprecated

##These are not compatible with WYSIWYG
$wgFCKEditorExcludedNamespaces[] = NS_MEDIAWIKI;
$wgFCKEditorExcludedNamespaces[] = NS_TEMPLATE;
#13.11.13<-

#17.01.14->
#WikiEditor may not be compatible with WYSIWYG editor, use it with caution.
require_once( "$IP/extensions/WikiEditor/WikiEditor.php" );

# Enables/disables use of WikiEditor by default but still allow users to disable it in preferences
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;

# Displays the Preview and Changes tabs
$wgDefaultUserOptions['wikieditor-preview'] = 0;

# Displays the Publish and Cancel buttons on the top right side
$wgDefaultUserOptions['wikieditor-publish'] = 0;
#17.01.14<-

#27.03.14->
#This was required by SemanticMediaWiki extension in MW 1.22.4 to prevent startup error:
$wgLocalisationUpdateDirectory = "$IP/cache";

#These are for SemanticForms. Wysiwyg is not fully compatiple with SemanticForms and SemanticMediawiki,
#so this is experimental feature.
#enableSemantics( );
#include_once( "$IP/extensions/SemanticForms/SemanticForms.php" );

#Optional excludes of wysiwyg in case SemanticForms and SemanticMediawiki are installed:
#$wgFCKEditorExcludedNamespaces[] = SF_NS_FORM;
#$wgFCKEditorExcludedNamespaces[] = SMW_NS_PROPERTY;
#27.03.14<-

#06.02.15->
#Setting value of following variables eq. to 1 will cause wikitext text blocks
#within specified tags to be displayed as image- element in wysiwyg mode.
#Value eq. to 0 makes texts inside these tags editable directly as text in wysiwyg mode
#using pre- parent tag + child tag.
$wgFCKEditorSpecialElementWithPreTag   = 0; // 1= <pre> tags with attributes only => img- element
#06.02.15<-

#26.02.15->
$wgFCKEditorSpecialElementWithTextTags = 0; // 1= <nowiki>, <source> and <syntaxhighlight> tags => img- element
#26.02.15<-

#24.03.16-> 
#Debug- mode of resource loader (use only for testing purposes):
#$wgResourceLoaderDebug = true;

#In case CKEDITOR is installed in some special place, define installation path 
#with $wgCKEditor_BASEPATH. If variable is undefined, value will be 'extensions/WYSIWYG/ckeditor/'.
#NOTE! Path must end with character '/' in linux (opsys. windows is untested).
#$wgCKEditor_BASEPATH = 'extensions/WYSIWYG/ckeditor/';
#24.03.16<-
